### ISSUE TITLE
Replace Sahara plugin with built-in snapshot support

### ISSUE THREAD

**Issue by AnthonyMastrean** [chocolatey/chocolatey-test-environment#10]
I don't see any automatic/scripted calls to `sandbox`, so it might just be updating the instructions.

https://www.vagrantup.com/docs/cli/snapshot.html

**Comment by ferventcoder** [comment]
We don't use the built in sandbox - as it stands (if you've been following the issues with native sandbox support), it wasn't created correctly.

**Comment by ferventcoder** [comment]
https://github.com/mitchellh/vagrant/issues/6752#issuecomment-169039915

**Comment by ferventcoder** [comment]
And a start in the right direction - https://github.com/mitchellh/vagrant/pull/6879

**Comment by ferventcoder** [comment]
Clarification: "Correctly" means it will reset the box to the prior state and not do anything more.

**Comment by AnthonyMastrean** [comment]
Wow, I had not seen these discussions yet. I'm literally just starting to play with snapshots and haven't gotten this far :)

**Comment by ferventcoder** [comment]
Closing for now.
