### ISSUE TITLE
InstallChocolatey.ps1 throwing exception during 'vagrant up'

### ISSUE THREAD

**Issue by CalvinAllen** [chocolatey/chocolatey-test-environment#11]
Followed the steps to the T, but when I get to the point where InstallChocolatey.ps1 is being ran, I get an exception.  Weird thing is, I can go into the box after it happens, and run the same command/ps1 file and it works fine.

Gist: https://gist.github.com/CalvinAllen/6dcea4306443a584e291b4f4079eea32

Maybe a weird networking issue?

**Comment by ferventcoder** [comment]
Possibly a weird networking issue - looks like it had issues installing choco. :/

**Comment by ferventcoder** [comment]
Are you still running into this?

**Comment by CalvinAllen** [comment]
I just did a `vagrant destory` and `vagrant up` and everything seemed to go fine. 

Must have been a fluke or something.

**Comment by ferventcoder** [comment]
If you see it again, please comment and we can reopen this for investigation.
